<a href="https://colab.research.google.com/github/natchanant-arch/Project_Savings_Cooperative/blob/Pandas/Cooperative_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

##1. `read_csv()` — โหลดข้อมูลจริงจากไฟล์

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/natchanant-arch/Project_Savings_Cooperative/First/%E0%B8%AA%E0%B8%AB%E0%B8%81%E0%B8%A3%E0%B8%93%E0%B9%8C%E0%B8%AD%E0%B8%AD%E0%B8%A1%E0%B8%97%E0%B8%A3%E0%B8%B1%E0%B8%9E%E0%B8%A2%E0%B9%8C.csv")
df

,Unnamed: 0,txn_id,queue_number,date,customer_name,account_number,transaction_type,amount,balance_after,status,target_account
0,0,1,A-001,22/08/2026,ชิดชนก เยาวธนโชค,607-8-71898-0,ฝากเงิน,355.29,1591.73,สำเร็จ,-
1,1,2,A-002,22/08/2026,พุทธิพงษ์ ดัตพันธุ์,880-1-68377-0,ถอนเงิน,1026.93,333.01,ไม่สำเร็จ (ยอดเงินไม่พอ),-
2,2,3,A-003,22/08/2026,เพ็ญยุภา แท่นทอง,131-1-13335-0,ฝากเงิน,534.65,3297.52,สำเร็จ,-
3,3,4,A-004,22/08/2026,นวรรษนันท์ ทวีเดช,640-4-67394-0,ถอนเงิน,511.54,1718.83,สำเร็จ,-
4,4,5,A-005,22/08/2026,ฌาฆีภัตฐ์ ธรรมนิยม,570-5-12816-0,โอนเงิน,756.83,745.49,ไม่สำเร็จ (ยอดเงินไม่พอ),987-6-64549-0
...,...,...,...,...,...,...,...,...,...,...,...
295,295,296,A-016,29/08/2026,อณัฐตา บุนยะศัพท์,932-2-62465-0,ฝากเงิน,1086.05,3550.65,สำเร็จ,-
296,296,297,A-017,29/08/2026,มนัญชยา ถนอมพล,767-8-97432-0,โอนเงิน,1465.40,152.77,ไม่สำเร็จ (ยอดเงินไม่พอ),987-6-46782-0
297,297,298,A-018,29/08/2026,ฉลองชัย น้ำทิพย์,476-9-36993-0,ถอนเงิน,1331.30,1312.42,ไม่สำเร็จ (ยอดเงินไม่พอ),-
298,298,299,A-019,29/08/2026,ศศิรินทร์ อุลหัสสา,503-8-90825-0,ฝากเงิน,552.20,1371.47,สำเร็จ,-
299,299,300,A-020,29/08/2026,ฐิติณัฐฐา ศาสตร์ศิลป์,540-5-64453-0,โอนเงิน,202.96,123.83,ไม่สำเร็จ (ยอดเงินไม่พอ),987-6-27405-0

## 2. `info()` — ภาพรวมโครงสร้างข้อมูล

In [2]:
df.info()
# ตรวจสอบโครงสร้างข้อมูล ประเภทข้อมูล (Dtype) และเช็กค่าสูญหาย (Missing values)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        300 non-null    int64
 1   txn_id            300 non-null    int64
 2   queue_number      300 non-null    object
 3   date              300 non-null    object
 4   customer_name     300 non-null    object
 5   account_number    300 non-null    object
 6   transaction_type  300 non-null    object
 7   amount            300 non-null    float64
 8   balance_after     300 non-null    float64
 9   status            300 non-null    object
 10  target_account    300 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 25.9+ KB

## 3. `describe()` — สถิติพื้นฐาน

In [3]:
df.describe()
# คำนวณสถิติพื้นฐานเชิงตัวเลข (เช่น ค่าเฉลี่ย, ค่าต่ำสุด-สูงสุด)

       Unnamed: 0      txn_id       amount  balance_after
count  300.000000  300.000000   300.000000     300.000000
mean   149.500000  150.500000  1043.181567    1546.270867
std     86.746758   86.746758   543.460379    1107.400815
min      0.000000    1.000000   106.690000       2.680000
25%     74.750000   75.750000   551.877500     653.167500
50%    149.500000  150.500000  1081.430000    1280.070000
75%    224.250000  225.250000  1514.660000    2336.762500
max    299.000000  300.000000  1985.830000    4481.410000

##  4.`groupby() + agg()`

<h4>คำถามทางธุรกิจสำหรับสหกรณ์ออมทรัพย์</h4>

* ยอดเงินรวม ยอดเงินเฉลี่ย ยอดเงินสูงสุด และจำนวนรายการธุรกรรมของแต่ละประเภทธุรกรรม (ฝาก ถอน โอน) เป็นเท่าไหร่? (เฉพาะรายการที่สำเร็จ)

In [4]:
# จัดกลุ่มตามประเภทธุรกรรม และคำนวณนับจำนวน ผลรวม ค่าเฉลี่ย และยอดสูงสุด
print("=== สรุปภาพรวมตามประเภทธุรกรรม ===")
summary_by_type = df[df["status"] == "สำเร็จ"] .groupby("transaction_type").agg(
    จำนวนรายการ=("txn_id", "count"),
    ยอดเงินรวม=("amount", "sum"),
    ยอดเงินเฉลี่ย=("amount", "mean"),
    ยอดเงินสูงสุด=("amount", "max")
).reset_index()

display(summary_by_type)

=== สรุปภาพรวมตามประเภทธุรกรรม ===

  transaction_type  จํานวนรายการ  ยอดเงินรวม  ยอดเงินเฉลี่ย  ยอดเงินสูงสุด
0          ถอนเงิน            37    24068.97     650.512703        1442.54
1          ฝากเงิน           102   101896.45     998.984804        1954.07
2          โอนเงิน            35    22646.61     647.046000        1261.44